#Initializing Different Types of Arrays


In [18]:
#All zeros matrix
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#Any other number 
#np.full((shape-r,c),number)
np.full((2,3),99,dtype="float32")

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [11]:
#Random decimal number
np.random.rand(4,2)

array([[0.54623935, 0.48910897],
       [0.95174528, 0.13250259],
       [0.11768711, 0.28705203],
       [0.15611878, 0.73106715]])

In [13]:
#random integer value between 0 and 7
np.random.randint(7)

1

In [15]:
#random integer value within some shape
np.random.randint(8,size=(3,3))

array([[4, 7, 7],
       [0, 1, 0],
       [4, 6, 7]])

In [17]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Be careful when copying arrays to avoid erros

In [20]:
a=np.array([1,2,3])
b=a.copy()
b[1]=100
print(b)
print(a)

[  1 100   3]
[1 2 3]
