In [31]:
#Acess Elements/Indexing
import numpy as np

In [3]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) #2D
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
#Get a specific element[row,column]
a[0,5]

6

In [6]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [8]:
#Getting a little more fancy[row, startindex:endindex:stepsize]
a[0,1:5:2]

array([2, 4])

In [13]:
#Change an element
a[1,5]=20
print(a)

a[:,2]=[1,2] #In a column
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [18]:
#3-d example

b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [21]:
#Get Specific element(work outside in)
b[0,2,0]

7

In [22]:
#replace
b[0,0,0]=3
print(b)

[[[3 2 3]
  [4 5 6]
  [7 8 9]]]
