In [1]:
import numpy as np


In [16]:
a=np.array([1,2,3], dtype='int16') #we can define type if we want
print(a)

[1 2 3]


In [8]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) #2d array
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get dimension
print(a.ndim)

1


In [11]:
#Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [12]:
#Get type
a.dtype

dtype('int32')

In [22]:
#Get size(in terms of bytes)
print(a.itemsize) 
print(b.itemsize) #Floats are bigger in size

2
8


In [20]:
#Get total size
a.nbytes

6