Reorganizing Arrays

In [1]:
import numpy as np
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
after=before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#Vertical stacking
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack((v1,v2))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
#Horizontal stacking
h1=np.ones((2,2))
h2=np.zeros((2,2))
h1


array([[1., 1.],
       [1., 1.]])

In [14]:
np.hstack((h1,h2))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

Miscellaneous

Load Data from File

In [2]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)



[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [3]:
#Boolean Masking and Advanced Indexing

print(filedata[filedata >50])

print ((filedata > 50) &(filedata <100))

[196  75 766  75  55 999  78  76  88]
[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
