Mathematics

In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a-2

array([-1,  0,  1,  2])

In [5]:
a*2

array([2, 4, 6, 8])

In [6]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b=np.array([3,4,5,6])
a+b

array([ 4,  6,  8, 10])

In [9]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [10]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [19]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
b=np.full((3,2),3)
print(b)

[[3 3]
 [3 3]
 [3 3]]


In [28]:
c=np.matmul(a,b)
print(c)

[[9. 9.]
 [9. 9.]]


In [30]:
#find the determinant
d=np.identity(3) 
np.linalg.det(d) #determinant of an identity matrix is 1

1.0

Statistics

In [34]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.min((stats),axis=1) #minimum of eac group

array([1, 4])

In [36]:
np.max(stats)

6

In [39]:
np.sum(stats) #sum of everything

21