Reorganizing Arrays

In [1]:
import numpy as np
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
after=before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#Vertical stacking
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack((v1,v2))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
#Horizontal stacking
h1=np.ones((2,2))
h2=np.zeros((2,2))
h1


array([[1., 1.],
       [1., 1.]])

In [14]:
np.hstack((h1,h2))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

Miscellaneous

Load Data from File

In [34]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)



OSError: data.txt not found.

In [32]:
#Boolean Masking and Advanced Indexing

#print(filedata[filedata >50])

print ((filedata > 50) &(filedata <100))

NameError: name 'filedata' is not defined